apiVersion: v1
kind: Service
metadata:
  namespace: dealspot-dev
  name: trend-board
  labels:
    part-of: dealspot
    component: backend-server
    name: trend-board
    instance: trend-board-basic
    version: "0.0.1"
    managed-by: kubectl
spec:
  selector:
    part-of: dealspot
    component: backend-server
    name: trend-board
    instance: trend-board-basic
  ports:
    - port: 80
      targetPort: http
      nodePort: 30080
  type: NodePort
