apiVersion: v1
kind: Secret
metadata:
  namespace: dealspot-dev
  name: trend-board-secret
  labels:
    part-of: dealspot
    component: backend-server
    name: trend-board
    instance: trend-board-basic
    version: "0.0.1"
    managed-by: kubectl
stringData:
  DB_URL: "jdbc:mysql://mysql:3306/board_dev?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
