apiVersion: v1
kind: Service
metadata:
  namespace: dealspot-dev
  name: mysql
  labels:
    part-of: dealspot
    component: database
    name: mysql
    instance: mysql-basic
    version: "8.0"
    managed-by: kubectl
spec:
  selector:
    part-of: dealspot
    component: database
    name: mysql
    instance: mysql-basic
  ports:
    - port: 3306
      targetPort: mysql
  type: ClusterIP
