apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "trend-board.fullname" . }}-secret
  labels:
    {{- include "trend-board.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
